### PR TITLE
Inline Comments

### PR DESCRIPTION
**Pull request by cgiffard**
I had always assumed that CSSTree would place comments in the AST according to where they fell in the document, and was a little surprised when I discovered this wasn't the case.

I wasn't sure whether the comments were left out-of-band for a reason.

In any case, I've made a change that would bring them inline, submitted for your consideration. Regardless of whether you decide to merge this PR, or attack this your own way, it'd be nice for comments to be built into the AST like any other construct in the document.

The test suite passes locally without issue.

### CODE REVIEW

**Comment by codenothing** [comment]
The reason I had left them out was becuase I couldn't find a good way to handle an inner comment of a value

``` css
.some-class {
  font-size: /* Inner Comment */ 14px;
}
```

I'll definitely check this out and get back to you. Looks like it's failing on travis.

**Comment by cgiffard** [comment]
That's weird, none of the files tests actually run on my system.

There's two ways you could handle the inner-comment case, I think:
- You could append the comment in the tree prior to the rule in question; or
- You could permit comment branches inside rules, and put them in there.

Either way is fine with me. This pull will enable the former.

**Comment by codenothing** [comment]
I'm going to pass on this one. Thanks for the input, but I feel another approach in 0.0.4 will be better.

**Comment by timoxley** [comment]
@codenothing what are your thoughts on an alternative here?

**Pull request closed without merging**
